name: Build TC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build TC
        run: |
          wget https://raw.githubusercontent.com/neophyte721/Android-CI/main/clang.sh
          bash clang.sh

        env:
          LLVM_NAME: ${{ secrets.LLVM_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
